// JobCategoryList.tsx
// Comprehensive list of software development job categories

export const JOB_CATEGORIES = [
  // Frontend Development
  'Frontend Development',
  'React Development',
  'Angular Development',
  'Vue.js Development',
  'Svelte Development',
  'Next.js Development',
  'Nuxt.js Development',
  'JavaScript Development',
  'TypeScript Development',
  'HTML/CSS Development',
  'SASS/SCSS Development',
  'Tailwind CSS Development',
  'Bootstrap Development',
  'Material UI Development',
  'Responsive Web Design',
  'Progressive Web Apps (PWA)',
  'Single Page Applications (SPA)',
  'Component Library Development',
  'Frontend Performance Optimization',
  'Cross-browser Compatibility',
  'Accessibility (a11y) Development',
  'Web Animation Development',
  'CSS-in-JS Development',
  'Micro-frontend Development',
  'Static Site Generation',
  
  // Backend Development
  'Backend Development',
  'Node.js Development',
  'Express.js Development',
  'Nest.js Development',
  'Python Development',
  'Django Development',
  'Flask Development',
  'FastAPI Development',
  'Java Development',
  'Spring Boot Development',
  'Spring Framework Development',
  'C# Development',
  '.NET Development',
  '.NET Core Development',
  'ASP.NET Development',
  'PHP Development',
  'Laravel Development',
  'Symfony Development',
  'CodeIgniter Development',
  'Ruby Development',
  'Ruby on Rails Development',
  'Go Development',
  'Gin Framework Development',
  'Rust Development',
  'Actix Web Development',
  'Scala Development',
  'Elixir Development',
  'Phoenix Framework Development',
  'Microservices Development',
  'Serverless Development',
  'GraphQL Development',
  'gRPC Development',
  
  // Full-Stack Development
  'Full-Stack Development',
  'MEAN Stack Development',
  'MERN Stack Development',
  'MEVN Stack Development',
  'LAMP Stack Development',
  'JAMstack Development',
  'T3 Stack Development',
  'Django + React Development',
  'Laravel + Vue Development',
  'Rails + React Development',
  'Spring Boot + Angular Development',
  'ASP.NET + React Development',
  'Full-Stack JavaScript Development',
  'Full-Stack Python Development',
  'Full-Stack Java Development',
  'Full-Stack C# Development',
  'Full-Stack PHP Development',
  
  // Mobile Development
  'Mobile Development',
  'iOS Development',
  'Swift Development',
  'SwiftUI Development',
  'Objective-C Development',
  'Android Development',
  'Kotlin Development',
  'Java Android Development',
  'React Native Development',
  'Flutter Development',
  'Ionic Development',
  'Xamarin Development',
  'Cordova/PhoneGap Development',
  'Mobile UI/UX Development',
  'Cross-platform Mobile Development',
  'Native Mobile Development',
  'Hybrid Mobile Development',
  'Mobile Game Development',
  'Mobile App Testing',
  'Mobile Performance Optimization',
  'Mobile Security Development',
  
  // Desktop Development
  'Desktop Development',
  'Electron Development',
  'Tauri Development',
  'Qt Development',
  'WPF Development',
  'WinUI Development',
  'JavaFX Development',
  'Swing Development',
  'GTK Development',
  'Tkinter Development',
  'PyQt Development',
  'Kivy Development',
  'C++ Desktop Development',
  'Cross-platform Desktop Development',
  'Native Desktop Development',
  'Desktop UI/UX Development',
  
  // Game Development
  'Game Development',
  'Unity Development',
  'Unreal Engine Development',
  'Godot Development',
  'Game Engine Development',
  'C# Game Development',
  'C++ Game Development',
  'JavaScript Game Development',
  'Python Game Development',
  'Web Game Development',
  'VR Game Development',
  'AR Game Development',
  '2D Game Development',
  '3D Game Development',
  'Indie Game Development',
  'Multiplayer Game Development',
  'Game Physics Development',
  'Game AI Development',
  'Game Networking',
  'Game Optimization',
  'Game Porting',
  
  // Database Development
  'Database Development',
  'MySQL Development',
  'PostgreSQL Development',
  'MongoDB Development',
  'Redis Development',
  'SQLite Development',
  'Microsoft SQL Server Development',
  'Oracle Database Development',
  'Cassandra Development',
  'DynamoDB Development',
  'Firebase Development',
  'Supabase Development',
  'Neo4j Development',
  'InfluxDB Development',
  'CouchDB Development',
  'Database Design',
  'Database Optimization',
  'Data Modeling',
  'Database Migration',
  'NoSQL Development',
  'SQL Development',
  'Database Administration',
  'Data Warehousing',
  'ETL Development',
  'Database Security',
  
  // DevOps & Infrastructure
  'DevOps',
  'AWS Development',
  'Azure Development',
  'Google Cloud Platform (GCP)',
  'Docker Development',
  'Kubernetes Development',
  'Terraform Development',
  'Ansible Development',
  'Jenkins Development',
  'GitLab CI/CD',
  'GitHub Actions',
  'CircleCI Development',
  'Travis CI Development',
  'Infrastructure as Code (IaC)',
  'Container Orchestration',
  'Microservices Deployment',
  'Serverless Deployment',
  'Cloud Architecture',
  'Cloud Migration',
  'Monitoring & Logging',
  'Performance Monitoring',
  'System Administration',
  'Linux Administration',
  'Network Administration',
  'Load Balancing',
  'Auto-scaling',
  'Backup & Recovery',
  
  // API Development
  'API Development',
  'REST API Development',
  'GraphQL API Development',
  'WebSocket Development',
  'gRPC API Development',
  'OpenAPI/Swagger Development',
  'API Gateway Development',
  'Microservices API Development',
  'Third-party API Integration',
  'Payment API Integration',
  'Social Media API Integration',
  'Google APIs Integration',
  'AWS API Integration',
  'Stripe API Integration',
  'Twilio API Integration',
  'SendGrid API Integration',
  'OAuth Implementation',
  'JWT Authentication',
  'API Security',
  'API Testing',
  'API Documentation',
  'API Rate Limiting',
  'API Versioning',
  'Webhook Development',
  
  // E-commerce Development
  'E-commerce Development',
  'Shopify Development',
  'WooCommerce Development',
  'Magento Development',
  'BigCommerce Development',
  'Prestashop Development',
  'Custom E-commerce Development',
  'Headless E-commerce',
  'Multi-vendor Marketplace',
  'Payment Gateway Integration',
  'Inventory Management System',
  'Order Management System',
  'Shopping Cart Development',
  'Product Catalog Development',
  'E-commerce Mobile App',
  'E-commerce Analytics',
  'E-commerce SEO',
  'E-commerce Security',
  
  // CMS Development
  'CMS Development',
  'WordPress Development',
  'Custom WordPress Themes',
  'WordPress Plugin Development',
  'Headless WordPress',
  'Drupal Development',
  'Joomla Development',
  'Strapi Development',
  'Contentful Development',
  'Sanity CMS Development',
  'Ghost CMS Development',
  'Craft CMS Development',
  'Wagtail CMS Development',
  'Custom CMS Development',
  'Headless CMS Development',
  'CMS Migration',
  'CMS Optimization',
  'CMS Security',
  
  // Testing & Quality Assurance
  'Software Testing',
  'Test Automation',
  'Unit Testing',
  'Integration Testing',
  'End-to-End Testing',
  'Performance Testing',
  'Load Testing',
  'Security Testing',
  'Regression Testing',
  'Selenium Testing',
  'Cypress Testing',
  'Jest Testing',
  'Playwright Testing',
  'Postman Testing',
  'JUnit Testing',
  'PyTest Testing',
  'Test-Driven Development (TDD)',
  'Behavior-Driven Development (BDD)',
  'Quality Assurance (QA)',
  'Bug Tracking & Reporting',
  'Test Case Design',
  'Test Planning',
  'Code Review',
  
  // Data Science & AI
  'Data Science',
  'Machine Learning',
  'Deep Learning',
  'Artificial Intelligence',
  'Natural Language Processing (NLP)',
  'Computer Vision',
  'Data Analysis',
  'Data Engineering',
  'Big Data Development',
  'Python Data Science',
  'R Programming',
  'TensorFlow Development',
  'PyTorch Development',
  'Scikit-learn Development',
  'Pandas Development',
  'NumPy Development',
  'Jupyter Notebooks',
  'Data Visualization',
  'Matplotlib Development',
  'Plotly Development',
  'D3.js Development',
  'Business Intelligence',
  'Predictive Analytics',
  'Statistical Analysis',
  'Data Mining',
  'Feature Engineering',
  'Model Deployment',
  'MLOps',
  'AI Model Training',
  'Chatbot Development',
  'Recommendation Systems',
  
  // Cybersecurity
  'Cybersecurity Development',
  'Security Auditing',
  'Penetration Testing',
  'Vulnerability Assessment',
  'Security Code Review',
  'Secure Coding Practices',
  'Authentication Systems',
  'Authorization Systems',
  'Encryption Implementation',
  'Security Monitoring',
  'Incident Response Systems',
  'Compliance Implementation',
  'GDPR Compliance',
  'SOC 2 Compliance',
  'OAuth/SAML Implementation',
  'Two-Factor Authentication',
  'Web Application Security',
  'Cloud Security',
  'Network Security',
  'Blockchain Security',
  
  // Blockchain & Web3
  'Blockchain Development',
  'Smart Contract Development',
  'Solidity Development',
  'Ethereum Development',
  'Bitcoin Development',
  'Web3 Development',
  'DeFi Development',
  'NFT Development',
  'Cryptocurrency Development',
  'Hyperledger Development',
  'Polygon Development',
  'Binance Smart Chain Development',
  'Cardano Development',
  'Solana Development',
  'dApp Development',
  'Crypto Wallet Development',
  'Blockchain Integration',
  'Token Development',
  'ICO/IDO Development',
  'DAO Development',
  'Cross-chain Development',
  'Web3 Frontend Development',
  
  // Emerging Technologies
  'AR/VR Development',
  'Augmented Reality Development',
  'Virtual Reality Development',
  'Mixed Reality Development',
  'Unity AR Development',
  'ARKit Development',
  'ARCore Development',
  'WebXR Development',
  'IoT Development',
  'Embedded Systems Development',
  'Raspberry Pi Development',
  'Arduino Development',
  'Edge Computing',
  'Real-time Systems',
  'Quantum Computing',
  'Voice Assistant Development',
  'Alexa Skills Development',
  'Google Assistant Development',
  'Computer Graphics',
  'WebGL Development',
  'Three.js Development',
  'Simulation Development',
  
  // Specialized Areas
  'Legacy System Modernization',
  'System Integration',
  'Enterprise Software Development',
  'SaaS Development',
  'Multi-tenant Architecture',
  'Real-time Applications',
  'WebRTC Development',
  'Video Streaming Development',
  'Live Chat Development',
  'Notification Systems',
  'Search Engine Development',
  'Elasticsearch Development',
  'Recommendation Engines',
  'Content Delivery Networks (CDN)',
  'Caching Systems',
  'Message Queue Systems',
  'Event-driven Architecture',
  'CQRS Implementation',
  'Domain-driven Design (DDD)',
  'Clean Architecture',
  'Hexagonal Architecture',
  'Microservices Architecture',
  'Monolith to Microservices Migration',
  'Code Refactoring',
  'Scalability Engineering',
  'High Availability Systems',
  'Disaster Recovery Systems',
  'Internationalization (i18n)',
  'Localization (l10n)',
  'Multi-language Applications',
  'Accessibility Implementation',
  'Progressive Enhancement',
  'Graceful Degradation',
  'Cross-platform Development',
  'Code Migration',
  'Version Control Systems',
  'Git Workflow Implementation',
  'Documentation Systems',
  'Technical Writing',
  'Code Generation',
  'Automation Scripts',
  'Build Systems',
  'Package Management',
  'Dependency Management',
  'Software Architecture',
  'System Design',
  'Technical Consulting',
  'Code Audit',
  'Technology Stack Selection',
  'Other Software Development'
];